name: Commit workflow
run-name: Executing every commit required actions (tests, static analysis...) 🚀
on: [push]
jobs:
  docker-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests with docker-compose
        run: docker-compose up --build tests